import Head from 'next/head'
import Nav from '../../components/landing/nav'
import Footer from '../../components/footer'

export default function LandingLayout({ children }) {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>OPSAP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="flex-grow">{children}</main>
      <Footer />
    </div>
  )
}
